### ISSUE TITLE
Sending a message that begins with italics marked down with _ will incorrectly trigger the bot

### ISSUE THREAD

**Issue by is-sorry** [pengowray/sprinto#10]
#### Issue description
Sending a message in a chat that begins with the _ Markdown sign (for example, `_who are you_`) will cause the bot to mistake it for a command.

#### Steps to reproduce the issue

1.  Send `_who knew_` in any channel where the bot is active

#### What's the expected result?

- The bot ignores the message.

#### What's the actual result?

- The bot will respond as if he is invoked

#### Additional details / screenshot
![image](https://user-images.githubusercontent.com/32669219/109316502-5dba2b80-7854-11eb-8f50-aaaa41dbae2b.png)

**Comment by pengowray** [comment]
Heya, thanks for the bug report. 

Yeah, this is a problem. I've partly fixed it, and many of Sprinto's main commands will squelch the response if there's a second underscore, but it's not 100%, as you've found. Error messages from Sprinto are always dropped at least, but responses to some simple commands like `_who` still make it through.

Some work-arounds:

* If you're an admin, stop Sprinto listening in channels where he's not used (remove his Read Messages permission). It's also good privacy practice to stop bots listening to all messages in all channels.
* use * instead of _ for italics, e.g. `*who knew*`

Discord has recently added "slash commands", and once I've had time to implement them it should fix the problem better. Right now I can't really justify spending as much time working on Sprinto as I'd like, so development is the backburner while I find myself a steady income. But hope to get back to it soon.
