### ISSUE TITLE
Increase the time limit for sprints

### ISSUE THREAD

**Issue by Editux** [pengowray/sprinto#11]
The Sprinto bot is great but it's would be better if the time limit of the sprint can be more that 1 hour.

Perhaps it's one of the reason that the user will be confused and put down 

```
// which bot will make sprint for 2 minutes instead of 2 hours
_sprint for 2 
```
Instead of 

```
_sprint for 120
```
In anycase if it's possible to increase time limit for 2 hours or even 24 hours.

Would be awesome for the extreme sprinters!

**Comment by pengowray** [comment]
Yes, you're right, there's a few confusing things when a sprint is longer than an hour, but you can still run a two hour sprint with any of the following:

```
_sprint for 2 hours please

_sprint 120 pls

_sprint megathon
```

Currently 2 hours is the limit though. The main reason for not adding longer sprints is it makes maintenance / development more difficult as occasionally I'll need to wait for all sprints to end before restarting the bot, though this only happens very rarely. Also because I don't have fine grained permissions, it stops a rogue user starting a long sprint when/where they shoudn't.

Hope that helps

**Comment by Editux** [comment]
Thank you for your answer.
Well I hope one day something changes that would make development and maintenence easier that it's would be easier maintain longer sprints.
