### ISSUE TITLE
Remove users who are no longer present on the server

### ISSUE THREAD

**Issue by dom-henjes** [pengowray/sprinto#13]
I'm on multiple writing servers where some members have used the `_always` command and then left the server. In some cases there are even users who've subsequently deleted their accounts. The `_forgetuser <user>` command doesn't seem to work in this case. Is there either a workaround I could try, or any chance of a new feature being added to address this? A manual `_stop_pinging_users_who_arent_on_this_server` (probably with a snappier name), for example, would allow moderators to clean up the list of pings.

Not that this is currently an issue, but there's a possibility of users joining a server, adding themselves to the 'always pinged' list, then leaving the server and changing their name to something inappropriate, and there isn't (as far as I'm aware) currently a way for moderators to deal with it apart from manually removing and re-adding the bot, followed by reconfiguring it.

**Comment by pengowray** [comment]
Hi Dom,

The "forgetuser" command is a bit awkward, but it should work if you specify their user ID. 

`_forgetuser 123456789`

Don't include @ or ! or <>'s or anything else. If you can't find their user ID number you might need to turn on developer tools in Discord to expose it.

In the past I attempted to get Sprinto to automatically remove users who are no longer on the server, but unfortunately it didn't work. And since then, Discord has made it more difficult to get lists of who is on a server (or not on a server), or to get their username when they're not on a server, so it's become more difficult and awkward to forget those who have gone. Sorry about that.

Hope that helps.

**Comment by dom-henjes** [comment]
Thanks, that's worked! Do you mind if I set up a pull request to add this to the documentation?

**Comment by pengowray** [comment]
It's hidden away there under: https://github.com/pengowray/sprinto/wiki/SprintMC

But if you want to add it somewhere more obvious, that would be great.
