### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by AgentFulcrum** [pengowray/sprinto#17]
None of the commands for sprinto appear to be working. I've tried both the _ and / and tried using spaces as I saw that suggested in another post. Is their a known issue right now?

**Comment by citrusella** [comment]
Even if slash commands are on (I wouldn't know because of the following issue), people who need to use the legacy chat mode can't use slash commands (other than built-into-Discord ones like /shrug) AFAIK. You *should* be able to directly mention sprinto (i.e. `@Sprinto` and then the command with no prefix, so it would look sort of like `@Sprinto join 645` if you were joining a sprint with 645 starting words). I can verify that works at least because I just tried it.

**Comment by AgentFulcrum** [comment]
> 

I tried that and that did not seem to work either. I was trying to start a sprint and no one seems to be able to in the discord.

**Comment by pengowray** [comment]
Hi, . I can't suggest one thing because unfortunately there's a heap of of gotchas that might make Sprinto appear broken.
I've just updated my post which gives tips on using slash command:

https://www.patreon.com/posts/71439355

Let me know if you're still having problems though.
