### ISSUE TITLE
Sprinto slash commands won't respond in one specific server, only on mobile

### ISSUE THREAD

**Issue by ectokit** [pengowray/sprinto#25]
This bug seems to be mimicking the site-wide bot issue that was reported Jan 25, 2023 (https://github.com/pengowray/sprinto/issues/21) I am having this exact same problem except it's hyper-local instead of site-wide, and currently only affecting Sprinto bot. This issue is currently only occurring on one server, on mobile, and affects all users in that server

I can use the ```@sprinto sprint for 15``` fix mentioned in the Jan 2023 post without issue, so we can still sprint, but the slash commands do not work. Me and one other user (who has mod permissions, whereas I do not) tested it within our problem server, and then we tested Sprinto independently in two different servers on mobile, one private, one public, and slash commands worked just fine. We have no issues anywhere, in our problem server or elsewhere, on desktop.

As of posting this, there are currently no bug reports on https://discordstatus.com/

Because I know you'll probably need these since this seems to be a super specific issue, here are the server and channel IDs:
server ID: 557811738888896513
channel ID: 557825629634953218

**Comment by pengowray** [comment]
Can I just clarify the issue? Are Sprinto's slash commands not visible at all after typing `/` or `/sprint` ?

My best guess is it could be a permissions problem. Try having the Sprinto "re-invited" to the server to fix permissions. The easiest way is for a mod to view Sprinto's profile in Discord and click "+Add App", and choose your server again (you don't need to kick Sprinto out first to reinvite him), and that should fix most issues. But there's a bunch of other places where Discord permissions are set for the server, bots (under "integrations"), channel permissions, and the user/group permissions. I tried to list how to set them all in this post: https://www.patreon.com/posts/71439355 Unfortunately it's a bit tricky to check if everything is aligned so that everything works. Let me know how you go

**Comment by ectokit** [comment]
Nothing was visible from Sprinto after only typing ```/```.

However, another server member commented that a different server was having a similar issue, but when we went to check the bug again at about 19:45 EST, it had resolved itself on its own with no intervention from us. (None of the mods with permissions for bots were online). As of 23:30 EST, there are currently no further problems? So I'm not sure if this was weird, patchy Discord outage, or what really happened here 😅 But it seems like it's all systems go, now!

**Comment by pengowray** [comment]
Thanks for letting me know! Seems very odd. I wish there was some better way to monitor it or do something about it.

Guess I'll close this for now.
