### ISSUE TITLE
Automatically add initiator of sprint to sprint

### ISSUE THREAD

**Issue by sammbeller** [pengowray/sprinto#3]
Just got bit by this. Forgot to join the sprint after starting one. I think it should probably automatically add whoever starts the sprint to the sprint.

**Comment by pengowray** [comment]
I've gone back and forth on it before, but trhe way it is seems best. Sprinto tries to warn you in case you forgot to join by pinging you when the sprint starts and ends. e.g. "@yourname (not joined)"

It's like this so other people in the channel can easily follow your lead and join too without having to look up documentation on how to do it. Unfortunately if you're running sprints by yourself this gives you an extra step.

Also it avoids mistakes from Sprinto having to guess what you meant your starting word count to be. 

So, sorry it can be annoying but there are reasons and I think overall it works better this way, so that's how it is.

**Comment by sammbeller** [comment]
Fair enough. Thanks for the response.
